# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "devutils"
mod.name = "devutils"
mod.group = "net.kr1v.devutils"
mod.version = "0.0.2"

deps.fabric_loader = "0.19.3"
deps.malilib_api = "0.8.3"
loomx.loom_version = "1.17-SNAPSHOT"