name: Publish to maven

on: [workflow_dispatch]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-dept: 1

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Publish to maven
        run: ./gradlew build publish
        env:
          REPSY_USERNAME: ${{ secrets.REPSY_USERNAME }}
          REPSY_TOKEN: ${{ secrets.REPSY_TOKEN }}
